version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: fitness-review-db
    environment:
      POSTGRES_DB: fitness_review
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: 